import 'package:get/get_navigation/src/root/internacionalization.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'hello': 'Hello',
          'welcome': 'Welcome to GetX',
          'language': 'Language: English',
          'hourly_weather': 'Hourly Weather',
          'clear': 'Clear',
          'details': 'Details',
          'm_s': 'm/s',
          'today': 'Today',
          'oct': 'Oct',
          '5_days_ahead': '5 Days Ahead',
        },
        'fr_FR': {
          'hello': 'Bonjour',
          'welcome': 'Bienvenue à GetX',
          'language': 'Langue : Français',
          'hourly_weather': 'Météo horaire',
          'clear': 'Clair',
          'details': 'Détails',
          'm_s': 'm/s',
          'today': 'Aujourd\'hui',
          'oct': 'Oct',
          '5_days_ahead': '5 Jours à l\'avance',
        },
        'hi_IN': {
          'hello': 'नमस्ते',
          'welcome': 'GetX में आपका स्वागत है',
          'language': 'भाषा: हिंदी',
          'hourly_weather': 'प्रति घंटे का मौसम',
          'clear': 'साफ',
          'details': 'विवरण',
          'm_s': 'मीटर प्रति सेकंड',
          'today': 'आज',
          'oct': 'अक्टूबर',
          '5_days_ahead': '5 दिन आगे',
        },
        'es_ES': {
          'hello': 'Hola',
          'welcome': 'Bienvenido a GetX',
          'language': 'Idioma: Español',
          'hourly_weather': 'Clima Horario',
          'clear': 'Despejado',
          'details': 'Detalles',
          'm_s': 'm/s',
          'today': 'Hoy',
          'oct': 'Oct',
          '5_days_ahead': '5 Días Por Delante',
        },
        'ur_PK': {
          'hello': 'ہیلو',
          'welcome': 'GetX میں خوش آمدید',
          'language': 'زبان: اردو',
          'hourly_weather': 'گھنٹے بھر کا موسم',
          'clear': 'صاف',
          'details': 'تفصیلات',
          'm_s': 'میٹر فی سیکنڈ',
          'today': 'آج',
          'oct': 'اکتوبر',
          '5_days_ahead': '5 دن آگاہی',
        },
        'de_DE': {
          'hello': 'Hallo',
          'welcome': 'Willkommen bei GetX',
          'language': 'Sprache: Deutsch',
          'hourly_weather': 'Stündliches Wetter',
          'clear': 'Klar',
          'details': 'Details',
          'm_s': 'm/s',
          'today': 'Heute',
          'oct': 'Okt',
          '5_days_ahead': '5 Tage im Voraus',
        },
        'ml_IN': {
          'hello': 'ഹലോ',
          'welcome': 'GetX-ലേക്ക് സ്വാഗതം',
          'language': 'ഭാഷ: മലയാളം',
          'hourly_weather': 'അന്തസമയ കാലാവസ്ഥ',
          'clear': 'സ്പष്ടമായ',
          'details': 'വിശദാംശങ്ങൾ',
          'm_s': 'മീറ്റർ/സെക്കന്റ്',
          'today': 'ഇന്ന്',
          'oct': 'ഒക്ടോ',
          '5_days_ahead': 'മുന്നത്തെ 5 ദിവസം',
        },
        'sa_IN': {
          'hello': 'नमस्कारः',
          'welcome': 'GetX आगच्छते स्वागतम्',
          'language': 'भाषा: संस्कृत',
          'hourly_weather': 'प्रतिघण्टा मौसमः',
          'clear': 'शुद्धम्',
          'details': 'विवरणाः',
          'm_s': 'मीटर/सेकंद्',
          'today': 'आजः',
          'oct': 'अक्टूबरः',
          '5_days_ahead': '5 दिनान्तरं',
        },
        'mr_IN': {
          'hello': 'नमस्कार',
          'welcome': 'GetX मध्ये स्वागत आहे',
          'language': 'भाषा: मराठी',
          'hourly_weather': 'प्रत्येक तासाला हवामान',
          'clear': 'स्पष्ट',
          'details': 'तपशील',
          'm_s': 'मीटर प्रति सेकंद',
          'today': 'आज',
          'oct': 'ऑक्टोबर',
          '5_days_ahead': '5 दिवसांच्या आधी',
        },
      };
}
