name: task2_t2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.3.3
  google_fonts: ^6.1.0
  new_version_plus: ^0.0.11
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.3
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  firebase_auth: ^4.10.1
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
          weight: 300
        - asset: assets/fonts/SF-Pro-Italic.ttf
          weight: 500
          style: italic

